# Generated by Django 5.2.1 on 2025-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsslider',
            name='css',
        ),
        migrations.RemoveField(
            model_name='cmsslider',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cmsslider',
            name='text',
        ),
        migrations.RemoveField(
            model_name='cmsslider',
            name='title',
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='slide_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS класс'),
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='slide_img',
            field=models.ImageField(default='', upload_to='sliderimg/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='slide_text',
            field=models.CharField(default='', max_length=200, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='slide_title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
